spring:
  profiles: pdn
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/platzi-market
    username: postgres
    password: 12345

server:
  port: 8091
