spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/platzi-market
    username: postgres
    password: 12345

server:
  port: 8090

logging:
  file:
   name: log-aplication.log